version: 2

sources:
  - name: raw_covid19
    schema: airbyte_schema
    database: covid19_database
    description: A replica of the covid19 demographics data from Google BigQuery Open data.
    tables:
      - name: stg_index
        columns:
          - name: _airbyte_stg_index_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: stg_demographics
        columns:
          - name: _airbyte_stg_demographics_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: stg_economy
        columns:
          - name: _airbyte_stg_economy_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null

      - name: stg_epidemiology
        columns:
          - name: _airbyte_stg_epidemiology_hashid
            description: Hash column based on the values in the record.
            tests:
              - unique
              - not_null



models:
  - name: base_index
    config:
      materialized: view  
    columns: 
      - name: country_name
        tests:
          - accepted_values:
              values: ['United States', 'Canada', 'Mexico']
              config:
                severity: warn

  - name: base_demographics
    config:
      materialized: view
    columns:
      - name: location_key
        tests:
          - unique
          - not_null

  - name: base_economy
    config:
      materialized: view
    columns:
      - name: location_key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - unique
          - not_null
 
  - name: base_epidemiology
    config:
      tags: ['daily']
      materialized: view
    columns:
      - name: location_key
        tests:
          - relationships:
              to: ref('base_index')
              field: location_key

